"""Auto-generate migration from current schema

Revision ID: f152172746c6
Revises: bf47e1f73400
Create Date: 2026-01-17 19:11:41.911048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f152172746c6'
down_revision: Union[str, Sequence[str], None] = 'bf47e1f73400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tag',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('color', sa.Text(), server_default=sa.text("'#6366f1'::text"), nullable=True),
    sa.PrimaryKeyConstraint('id', name='Tag_pkey')
    )
    op.create_index('Tag_name_idx', 'Tag', ['name'], unique=False)
    op.create_index('Tag_name_key', 'Tag', ['name'], unique=True)
    op.create_table('User',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('firstName', sa.Text(), nullable=True),
    sa.Column('lastName', sa.Text(), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='User_pkey')
    )
    op.create_index('User_email_idx', 'User', ['email'], unique=False)
    op.create_index('User_email_key', 'User', ['email'], unique=True)
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('migration_name', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('applied_steps_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name='_prisma_migrations_pkey')
    )
    op.create_table('Notification',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('isRead', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name='Notification_userId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Notification_pkey')
    )
    op.create_index('Notification_userId_isRead_idx', 'Notification', ['userId', 'isRead'], unique=False)
    op.create_table('Project',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('ownerId', sa.Text(), nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), server_default=sa.text("'#3b82f6'::text"), nullable=True),
    sa.Column('icon', sa.Text(), server_default=sa.text("'folder'::text"), nullable=True),
    sa.ForeignKeyConstraint(['ownerId'], ['User.id'], name='Project_ownerId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Project_pkey')
    )
    op.create_index('Project_ownerId_idx', 'Project', ['ownerId'], unique=False)
    op.create_table('ProjectMember',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('projectId', sa.Text(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='ProjectRole'), server_default=sa.text('\'MEMBER\'::"ProjectRole"'), nullable=False),
    sa.Column('joinedAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], name='ProjectMember_projectId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name='ProjectMember_userId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ProjectMember_pkey')
    )
    op.create_index('ProjectMember_projectId_idx', 'ProjectMember', ['projectId'], unique=False)
    op.create_index('ProjectMember_projectId_userId_key', 'ProjectMember', ['projectId', 'userId'], unique=True)
    op.create_index('ProjectMember_userId_idx', 'ProjectMember', ['userId'], unique=False)
    op.create_table('Task',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', name='TaskStatus'), server_default=sa.text('\'TODO\'::"TaskStatus"'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='TaskPriority'), server_default=sa.text('\'MEDIUM\'::"TaskPriority"'), nullable=False),
    sa.Column('projectId', sa.Text(), nullable=False),
    sa.Column('creatorId', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigneeId', sa.Text(), nullable=True),
    sa.Column('dueDate', postgresql.TIMESTAMP(precision=3), nullable=True),
    sa.ForeignKeyConstraint(['assigneeId'], ['User.id'], name='Task_assigneeId_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creatorId'], ['User.id'], name='Task_creatorId_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], name='Task_projectId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Task_pkey')
    )
    op.create_index('Task_assigneeId_idx', 'Task', ['assigneeId'], unique=False)
    op.create_index('Task_creatorId_idx', 'Task', ['creatorId'], unique=False)
    op.create_index('Task_dueDate_idx', 'Task', ['dueDate'], unique=False)
    op.create_index('Task_projectId_status_idx', 'Task', ['projectId', 'status'], unique=False)
    op.create_table('Activity',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('projectId', sa.Text(), nullable=True),
    sa.Column('taskId', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['projectId'], ['Project.id'], name='Activity_projectId_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['taskId'], ['Task.id'], name='Activity_taskId_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], name='Activity_userId_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='Activity_pkey')
    )
    op.create_index('Activity_createdAt_idx', 'Activity', ['createdAt'], unique=False)
    op.create_index('Activity_projectId_idx', 'Activity', ['projectId'], unique=False)
    op.create_index('Activity_taskId_idx', 'Activity', ['taskId'], unique=False)
    op.create_index('Activity_userId_idx', 'Activity', ['userId'], unique=False)
    op.create_table('Comment',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('taskId', sa.Text(), nullable=False),
    sa.Column('authorId', sa.Text(), nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.ForeignKeyConstraint(['authorId'], ['User.id'], name='Comment_authorId_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['taskId'], ['Task.id'], name='Comment_taskId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='Comment_pkey')
    )
    op.create_index('Comment_authorId_idx', 'Comment', ['authorId'], unique=False)
    op.create_index('Comment_taskId_idx', 'Comment', ['taskId'], unique=False)
    op.create_table('TaskTag',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('taskId', sa.Text(), nullable=False),
    sa.Column('tagId', sa.Text(), nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['tagId'], ['Tag.id'], name='TaskTag_tagId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taskId'], ['Task.id'], name='TaskTag_taskId_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='TaskTag_pkey')
    )
    op.create_index('TaskTag_tagId_idx', 'TaskTag', ['tagId'], unique=False)
    op.create_index('TaskTag_taskId_idx', 'TaskTag', ['taskId'], unique=False)
    op.create_index('TaskTag_taskId_tagId_key', 'TaskTag', ['taskId', 'tagId'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('TaskTag_taskId_tagId_key', table_name='TaskTag')
    op.drop_index('TaskTag_taskId_idx', table_name='TaskTag')
    op.drop_index('TaskTag_tagId_idx', table_name='TaskTag')
    op.drop_table('TaskTag')
    op.drop_index('Comment_taskId_idx', table_name='Comment')
    op.drop_index('Comment_authorId_idx', table_name='Comment')
    op.drop_table('Comment')
    op.drop_index('Activity_userId_idx', table_name='Activity')
    op.drop_index('Activity_taskId_idx', table_name='Activity')
    op.drop_index('Activity_projectId_idx', table_name='Activity')
    op.drop_index('Activity_createdAt_idx', table_name='Activity')
    op.drop_table('Activity')
    op.drop_index('Task_projectId_status_idx', table_name='Task')
    op.drop_index('Task_dueDate_idx', table_name='Task')
    op.drop_index('Task_creatorId_idx', table_name='Task')
    op.drop_index('Task_assigneeId_idx', table_name='Task')
    op.drop_table('Task')
    op.drop_index('ProjectMember_userId_idx', table_name='ProjectMember')
    op.drop_index('ProjectMember_projectId_userId_key', table_name='ProjectMember')
    op.drop_index('ProjectMember_projectId_idx', table_name='ProjectMember')
    op.drop_table('ProjectMember')
    op.drop_index('Project_ownerId_idx', table_name='Project')
    op.drop_table('Project')
    op.drop_index('Notification_userId_isRead_idx', table_name='Notification')
    op.drop_table('Notification')
    op.drop_table('_prisma_migrations')
    op.drop_index('User_email_key', table_name='User')
    op.drop_index('User_email_idx', table_name='User')
    op.drop_table('User')
    op.drop_index('Tag_name_key', table_name='Tag')
    op.drop_index('Tag_name_idx', table_name='Tag')
    op.drop_table('Tag')
    # ### end Alembic commands ###
